export const GET_LIST_PHONG_REQUEST = 'GET_LIST_PHONG_REQUEST';
export const GET_LIST_PHONG_SUCCESS = 'GET_LIST_PHONG_SUCCESS';
export const GET_LIST_PHONG_FAILURE = 'GET_LIST_PHONG_FAILURE';

export const ADD_LOAI_PHONG_REQUEST = 'ADD_LOAI_PHONG_REQUEST';
export const ADD_LOAI_PHONG_SUCCESS = 'ADD_LOAI_PHONG_SUCCESS';
export const ADD_LOAI_PHONG_FAILURE = 'ADD_LOAI_PHONG_FAILURE';

export const FIND_LOAI_PHONG_THEO_ID_REQUEST = 'FIND_LOAI_PHONG_THEO_ID_REQUEST';
export const FIND_LOAI_PHONG_THEO_ID_SUCCESS = 'FIND_LOAI_PHONG_THEO_ID_SUCCESS';
export const FIND_LOAI_PHONG_THEO_ID_FAILURE = 'FIND_LOAI_PHONG_THEO_ID_FAILURE';

export const DELETE_LOAI_PHONG_REQUEST = 'DELETE_LOAI_PHONG_REQUEST';
export const DELETE_LOAI_PHONG_SUCCESS = 'DELETE_LOAI_PHONG_SUCCESS';
export const DELETE_LOAI_PHONG_FAILURE = 'DELETE_LOAI_PHONG_FAILURE';
