//=================================LOAI PHÒNG=======================================//
export const GET_LIST_LOAI_PHONG_REQUEST = 'GET_LIST_LOAI_PHONG_REQUEST';
export const GET_LIST_LOAI_PHONG_SUCCESS = 'GET_LIST_LOAI_PHONG_SUCCESS';
export const GET_LIST_LOAI_PHONG_FAILURE = 'GET_LIST_LOAI_PHONG_FAILURE';

export const ADD_LOAI_PHONG_REQUEST = 'ADD_LOAI_PHONG_REQUEST';
export const ADD_LOAI_PHONG_SUCCESS = 'ADD_LOAI_PHONG_SUCCESS';
export const ADD_LOAI_PHONG_FAILURE = 'ADD_LOAI_PHONG_FAILURE';

export const FIND_LOAI_PHONG_THEO_ID_REQUEST = 'FIND_LOAI_PHONG_THEO_ID_REQUEST';
export const FIND_LOAI_PHONG_THEO_ID_SUCCESS = 'FIND_LOAI_PHONG_THEO_ID_SUCCESS';
export const FIND_LOAI_PHONG_THEO_ID_FAILURE = 'FIND_LOAI_PHONG_THEO_ID_FAILURE';

export const DELETE_LOAI_PHONG_THEO_ID_REQUEST = 'DELETE_LOAI_PHONG_THEO_ID_REQUEST';
export const DELETE_LOAI_PHONG_THEO_ID_SUCCESS = 'DELETE_LOAI_PHONG_THEO_ID_SUCCESS';
export const DELETE_LOAI_PHONG_THEO_ID_FAILURE = 'DELETE_LOAI_PHONG_THEO_ID_FAILURE';

export const UPDATE_LOAI_PHONG_THEO_ID_REQUEST = 'UPDATE_LOAI_PHONG_THEO_ID_REQUEST';
export const UPDATE_LOAI_PHONG_THEO_ID_SUCCESS = 'UPDATE_LOAI_PHONG_THEO_ID_SUCCESS';
export const UPDATE_LOAI_PHONG_THEO_ID_FAILURE = 'UPDATE_LOAI_PHONG_THEO_ID_FAILURE';


//=====================================PHÒNG=======================================//
export const GET_LIST_PHONG_REQUEST = 'GET_LIST_PHONG_REQUEST';
export const GET_LIST_PHONG_SUCCESS = 'GET_LIST_PHONG_SUCCESS';
export const GET_LIST_PHONG_FAILURE = 'GET_LIST_PHONG_FAILURE';

export const ADD_PHONG_REQUEST = 'ADD_PHONG_REQUEST';
export const ADD_PHONG_SUCCESS = 'ADD_PHONG_SUCCESS';
export const ADD_PHONG_FAILURE = 'ADD_PHONG_FAILURE';

export const FIND_PHONG_THEO_ID_REQUEST = 'FIND_PHONG_THEO_ID_REQUEST';
export const FIND_PHONG_THEO_ID_SUCCESS = 'FIND_PHONG_THEO_ID_SUCCESS';
export const FIND_PHONG_THEO_ID_FAILURE = 'FIND_PHONG_THEO_ID_FAILURE';

export const DELETE_PHONG_THEO_ID_REQUEST = 'DELETE_PHONG_THEO_ID_REQUEST';
export const DELETE_PHONG_THEO_ID_SUCCESS = 'DELETE_PHONG_THEO_ID_SUCCESS';
export const DELETE_PHONG_THEO_ID_FAILURE = 'DELETE_PHONG_THEO_ID_FAILURE';

export const UPDATE_PHONG_THEO_ID_REQUEST = 'UPDATE_PHONG_THEO_ID_REQUEST';
export const UPDATE_PHONG_THEO_ID_SUCCESS = 'UPDATE_PHONG_THEO_ID_SUCCESS';
export const UPDATE_PHONG_THEO_ID_FAILURE = 'UPDATE_PHONG_THEO_ID_FAILURE';

//=====================================CUSTOMER=======================================//
export const GET_LIST_KHACHHANG_REQUEST = 'GET_LIST_KHACHHANG_REQUEST';
export const GET_LIST_KHACHHANG_SUCCESS = 'GET_LIST_KHACHHANG_SUCCESS';
export const GET_LIST_KHACHHANG_FAILURE = 'GET_LIST_KHACHHANG_FAILURE';

export const ADD_KHACHHANG_REQUEST = 'ADD_KHACHHANG_REQUEST';
export const ADD_KHACHHANG_SUCCESS = 'ADD_KHACHHANG_SUCCESS';
export const ADD_KHACHHANG_FAILURE = 'ADD_KHACHHANG_FAILURE';
//=====================================CUSTOMER TYPE=======================================//
export const GET_LIST_LOAIKHACHHANG_REQUEST = 'GET_LIST_LOAIKHACHHANG_REQUEST';
export const GET_LIST_LOAIKHACHHANG_SUCCESS = 'GET_LIST_LOAIKHACHHANG_SUCCESS';
export const GET_LIST_LOAIKHACHHANG_FAILURE = 'GET_LIST_LOAIKHACHHANG_FAILURE';

export const ADD_LOAIKHACHHANG_REQUEST = 'ADD_LOAIKHACHHANG_REQUEST';
export const ADD_LOAIKHACHHANG_SUCCESS = 'ADD_LOAIKHACHHANG_SUCCESS';
export const ADD_LOAIKHACHHANG_FAILURE = 'ADD_LOAIKHACHHANG_FAILURE';

export const FIND_LOAIKHACHHANG_REQUEST = 'FIND_LOAIKHACHHANG_REQUEST';
export const FIND_LOAIKHACHHANG_SUCCESS = 'FIND_LOAIKHACHHANG_SUCCESS';
export const FIND_LOAIKHACHHANG_FAILURE = 'FIND_LOAIKHACHHANG_FAILURE';

export const DELETE_LOAIKHACHHANG_REQUEST = 'DELETE_LOAIKHACHHANG_REQUEST';
export const DELETE_LOAIKHACHHANG_SUCCESS = 'DELETE_LOAIKHACHHANG_SUCCESS';
export const DELETE_LOAIKHACHHANG_FAILURE = 'DELETE_LOAIKHACHHANG_FAILURE';

export const UPDATE_LOAIKHACHHANG_REQUEST = 'UPDATE_LOAIKHACHHANG_REQUEST';
export const UPDATE_LOAIKHACHHANG_SUCCESS = 'UPDATE_LOAIKHACHHANG_SUCCESS';
export const UPDATE_LOAIKHACHHANG_FAILURE = 'UPDATE_LOAIKHACHHANG_FAILURE';

//=====================================DEVICE=======================================//
export const GET_LIST_THIETBI_REQUEST = 'GET_LIST_THIETBI_REQUEST';
export const GET_LIST_THIETBI_SUCCESS = 'GET_LIST_THIETBI_SUCCESS';
export const GET_LIST_THIETBI_FAILURE = 'GET_LIST_THIETBI_FAILURE';

export const ADD_THIETBI_REQUEST = 'ADD_THIETBI_REQUEST';
export const ADD_THIETBI_SUCCESS = 'ADD_THIETBI_SUCCESS';
export const ADD_THIETBI_FAILURE = 'ADD_THIETBI_FAILURE';

//================================DEVICE TYPE =======================================//
export const GET_LIST_LOAITHIETBI_REQUEST = 'GET_LIST_LOAITHIETBI_REQUEST';
export const GET_LIST_LOAITHIETBI_SUCCESS = 'GET_LIST_LOAITHIETBI_SUCCESS';
export const GET_LIST_LOAITHIETBI_FAILURE = 'GET_LIST_LOAITHIETBI_FAILURE';

export const ADD_LOAITHIETBI_REQUEST = 'ADD_LOAITHIETBI_REQUEST';
export const ADD_LOAITHIETBI_SUCCESS = 'ADD_LOAITHIETBI_SUCCESS';
export const ADD_LOAITHIETBI_FAILURE = 'ADD_LOAITHIETBI_FAILURE';

export const FIND_LOAITHIETBI_THEO_ID_REQUEST = 'FIND_LOAITHIETBI_THEO_ID_REQUEST';
export const FIND_LOAITHIETBI_THEO_ID_SUCCESS = 'FIND_LOAITHIETBI_THEO_ID_SUCCESS';
export const FIND_LOAITHIETBI_THEO_ID_FAILURE = 'FIND_LOAITHIETBI_THEO_ID_FAILURE';

export const DELETE_LOAITHIETBI_REQUEST = 'DELETE_LOAITHIETBI_REQUEST';
export const DELETE_LOAITHIETBI_SUCCESS = 'DELETE_LOAITHIETBI_SUCCESS';
export const DELETE_LOAITHIETBI_FAILURE = 'DELETE_LOAITHIETBI_FAILURE';

export const UPDATE_LOAITHIETBI_REQUEST = 'UPDATE_LOAITHIETBI_REQUEST';
export const UPDATE_LOAITHIETBI_SUCCESS = 'UPDATE_LOAITHIETBI_SUCCESS';
export const UPDATE_LOAITHIETBI_FAILURE = 'UPDATE_LOAITHIETBI_FAILURE';


//=====================================BOOKING=======================================//
export const GET_DATPHONG_REQUEST = 'GET_DATPHONG_REQUEST';
export const GET_DATPHONG_SUCCESS = 'GET_DATPHONG_SUCCESS';
export const GET_DATPHONG_FAILURE = 'GET_DATPHONG_FAILURE';

export const GET_DATPHONG_ONLINE_REQUEST = 'GET_DATPHONG_ONLINE_REQUEST';
export const GET_DATPHONG_ONLINE_SUCCESS = 'GET_DATPHONG_ONLINE_SUCCESS';
export const GET_DATPHONG_ONLINE_FAILURE = 'GET_DATPHONG_ONLINE_FAILURE';

export const GET_DATPHONG_BY_PHONG_REQUEST = 'GET_DATPHONG_BY_PHONG_REQUEST';
export const GET_DATPHONG_BY_PHONG_SUCCESS = 'GET_DATPHONG_BY_PHONG_SUCCESS';
export const GET_DATPHONG_BY_PHONG_FAILURE = 'GET_DATPHONG_BY_PHONG_FAILURE';

export const ADD_DATPHONG_REQUEST = 'ADD_DATPHONG_REQUEST';
export const ADD_DATPHONG_SUCCESS = 'ADD_DATPHONG_SUCCESS';
export const ADD_DATPHONG_FAILURE = 'ADD_DATPHONG_FAILURE';

export const CHECKOUT_DATPHONG_REQUEST = 'CHECKOUT_DATPHONG_REQUEST';
export const CHECKOUT_DATPHONG_SUCCESS = 'CHECKOUT_DATPHONG_SUCCESS';
export const CHECKOUT_DATPHONG_FAILURE = 'CHECKOUT_DATPHONG_FAILURE';

export const CHECKIN_DATPHONG_REQUEST = 'CHECKIN_DATPHONG_REQUEST';
export const CHECKIN_DATPHONG_SUCCESS = 'CHECKIN_DATPHONG_SUCCESS';
export const CHECKIN_DATPHONG_FAILURE = 'CHECKIN_DATPHONG_FAILURE';

export const GET_THANHTOAN_BY_DATPHONG_REQUEST = 'GET_THANHTOAN_BY_DATPHONG_REQUEST';
export const GET_THANHTOAN_BY_DATPHONG_SUCCESS = 'GET_THANHTOAN_BY_DATPHONG_SUCCESS';
export const GET_THANHTOAN_BY_DATPHONG_FAILURE = 'GET_THANHTOAN_BY_DATPHONG_FAILURE';

export const ADD_THANHTOAN_REQUEST = 'ADD_THANHTOAN_REQUEST';
export const ADD_THANHTOAN_SUCCESS = 'ADD_THANHTOAN_SUCCESS';
export const ADD_THANHTOAN_FAILURE = 'ADD_THANHTOAN_FAILURE';

export const ADD_DICHVU_BY_PHONG_REQUEST = 'ADD_DICHVU_BY_PHONG_REQUEST';
export const ADD_DICHVU_BY_PHONG_SUCCESS = 'ADD_DICHVU_BY_PHONG_SUCCESS';
export const ADD_DICHVU_BY_PHONG_FAILURE = 'ADD_DICHVU_BY_PHONG_FAILURE';
//=====================================BOOKING=======================================//
export const PICK_CARD_PHONG = 'PICK_CARD_PHONG';

//==============================DICHVU=====================================//
export const GET_LIST_DICHVU_REQUEST = 'GET_LIST_DICHVU_REQUEST';
export const GET_LIST_DICHVU_SUCCESS = 'GET_LIST_DICHVU_SUCCESS';
export const GET_LIST_DICHVU_FAILURE = 'GET_LIST_DICHVU_FAILURE';

export const ADD_DICHVU_REQUEST = 'ADD_DICHVU_REQUEST';
export const ADD_DICHVU_SUCCESS = 'ADD_DICHVU_SUCCESS';
export const ADD_DICHVU_FAILURE = 'ADD_DICHVU_FAILURE';
