//=================================LOAI PHÒNG=======================================//
export const GET_LIST_LOAI_PHONG_REQUEST = 'GET_LIST_LOAI_PHONG_REQUEST';
export const GET_LIST_LOAI_PHONG_SUCCESS = 'GET_LIST_LOAI_PHONG_SUCCESS';
export const GET_LIST_LOAI_PHONG_FAILURE = 'GET_LIST_LOAI_PHONG_FAILURE';

export const ADD_LOAI_PHONG_REQUEST = 'ADD_LOAI_PHONG_REQUEST';
export const ADD_LOAI_PHONG_SUCCESS = 'ADD_LOAI_PHONG_SUCCESS';
export const ADD_LOAI_PHONG_FAILURE = 'ADD_LOAI_PHONG_FAILURE';

export const FIND_LOAI_PHONG_THEO_ID_REQUEST = 'FIND_LOAI_PHONG_THEO_ID_REQUEST';
export const FIND_LOAI_PHONG_THEO_ID_SUCCESS = 'FIND_LOAI_PHONG_THEO_ID_SUCCESS';
export const FIND_LOAI_PHONG_THEO_ID_FAILURE = 'FIND_LOAI_PHONG_THEO_ID_FAILURE';

export const DELETE_LOAI_PHONG_THEO_ID_REQUEST = 'DELETE_LOAI_PHONG_THEO_ID_REQUEST';
export const DELETE_LOAI_PHONG_THEO_ID_SUCCESS = 'DELETE_LOAI_PHONG_THEO_ID_SUCCESS';
export const DELETE_LOAI_PHONG_THEO_ID_FAILURE = 'DELETE_LOAI_PHONG_THEO_ID_FAILURE';

export const UPDATE_LOAI_PHONG_THEO_ID_REQUEST = 'UPDATE_LOAI_PHONG_THEO_ID_REQUEST';
export const UPDATE_LOAI_PHONG_THEO_ID_SUCCESS = 'UPDATE_LOAI_PHONG_THEO_ID_SUCCESS';
export const UPDATE_LOAI_PHONG_THEO_ID_FAILURE = 'UPDATE_LOAI_PHONG_THEO_ID_FAILURE';


//=====================================PHÒNG=======================================//
export const GET_LIST_PHONG_REQUEST = 'GET_LIST_PHONG_REQUEST';
export const GET_LIST_PHONG_SUCCESS = 'GET_LIST_PHONG_SUCCESS';
export const GET_LIST_PHONG_FAILURE = 'GET_LIST_PHONG_FAILURE';

//=====================================CUSTOMER=======================================//
export const GET_LIST_KHACHHANG_REQUEST = 'GET_LIST_KHACHHANG_REQUEST';
export const GET_LIST_KHACHHANG_SUCCESS = 'GET_LIST_KHACHHANG_SUCCESS';
export const GET_LIST_KHACHHANG_FAILURE = 'GET_LIST_KHACHHANG_FAILURE';

export const ADD_KHACHHANG_REQUEST = 'ADD_KHACHHANG_REQUEST';
export const ADD_KHACHHANG_SUCCESS = 'ADD_KHACHHANG_SUCCESS';
export const ADD_KHACHHANG_FAILURE = 'ADD_KHACHHANG_FAILURE';
//=====================================CUSTOMER TYPE=======================================//
export const GET_LIST_LOAIKHACHHANG_REQUEST = 'GET_LIST_LOAIKHACHHANG_REQUEST';
export const GET_LIST_LOAIKHACHHANG_SUCCESS = 'GET_LIST_LOAIKHACHHANG_SUCCESS';
export const GET_LIST_LOAIKHACHHANG_FAILURE = 'GET_LIST_LOAIKHACHHANG_FAILURE';

export const ADD_LOAIKHACHHANG_REQUEST = 'ADD_LOAIKHACHHANG_REQUEST';
export const ADD_LOAIKHACHHANG_SUCCESS = 'ADD_LOAIKHACHHANG_SUCCESS';
export const ADD_LOAIKHACHHANG_FAILURE = 'ADD_LOAIKHACHHANG_FAILURE';

export const FIND_LOAIKHACHHANG_REQUEST = 'FIND_LOAIKHACHHANG_REQUEST';
export const FIND_LOAIKHACHHANG_SUCCESS = 'FIND_LOAIKHACHHANG_SUCCESS';
export const FIND_LOAIKHACHHANG_FAILURE = 'FIND_LOAIKHACHHANG_FAILURE';

export const DELETE_LOAIKHACHHANG_REQUEST = 'DELETE_LOAIKHACHHANG_REQUEST';
export const DELETE_LOAIKHACHHANG_SUCCESS = 'DELETE_LOAIKHACHHANG_SUCCESS';
export const DELETE_LOAIKHACHHANG_FAILURE = 'DELETE_LOAIKHACHHANG_FAILURE';

export const UPDATE_LOAIKHACHHANG_REQUEST = 'UPDATE_LOAIKHACHHANG_REQUEST';
export const UPDATE_LOAIKHACHHANG_SUCCESS = 'UPDATE_LOAIKHACHHANG_SUCCESS';
export const UPDATE_LOAIKHACHHANG_FAILURE = 'UPDATE_LOAIKHACHHANG_FAILURE';

//=====================================REPAIR=======================================//
export const GET_LIST_HUHONG_REQUEST = 'GET_LIST_HUHONG_REQUEST';
export const GET_LIST_HUHONG_SUCCESS = 'GET_LIST_HUHONG_SUCCESS';
export const GET_LIST_HUHONG_FAILURE = 'GET_LIST_HUHONG_FAILURE';

export const ADD_HUHONG_REQUEST = 'ADD_HUHONG_REQUEST';
export const ADD_HUHONG_SUCCESS = 'ADD_HUHONG_SUCCESS';
export const ADD_HUHONG_FAILURE = 'ADD_HUHONG_FAILURE';
